// Shared Turkish/English interface translations. Turkish is the default.
const translations = {
  "SON HAT": "LAST LINE",
  "Kelime Savunması": "Word Defense",
  "Mouse Antrenmanı": "Mouse Training",
  "KELİME SAVUNMASI": "WORD DEFENSE",
  "MOUSE ANTRENMANI": "MOUSE TRAINING",
  "KLAVYE": "KEYBOARD",
  "Antrenman bölümü": "Training section",
  "Üzerine doğru yürüyen üç boyutlu robotlar": "Three-dimensional robots walking towards you",
  "KALAN SÜRE": "TIME LEFT",
  "ETKİSİZ HALE GETİRİLEN": "ROBOTS STOPPED",
  "SAVUNMA DURUMU": "DEFENSE STATUS",
  "SEKTÖR": "SECTOR",
  "Gece nöbeti": "Night watch",
  "Bir kelime.": "One word.",
  "Bir atış.": "One shot.",
  "Bir şans daha.": "One more chance.",
  "60 SANİYE BOYUNCA HATTI KORU": "HOLD THE LINE FOR 60 SECONDS",
  "En güçlü silahın,": "Your strongest weapon,",
  "kelimelerin.": "your words.",
  "Robotlar yaklaşıyor. Üzerlerindeki kelimeleri yaz,": "Robots are approaching. Type the words above them,",
  "hedefleri durdur ve son saniyeye kadar hayatta kal.": "stop the targets and survive until the last second.",
  "OYUN MODU": "GAME MODE",
  "Hayatta kal · 3 can": "Survival · 3 lives",
  "Hız turu · sınırsız can": "Speed round · unlimited lives",
  "ZORLUK": "DIFFICULTY",
  "Kolay": "Easy",
  "Orta": "Medium",
  "Zor": "Hard",
  "3 can. Robotları durdur ve 60 saniye boyunca hayatta kal.": "3 lives. Stop the robots and survive for 60 seconds.",
  "Sınırsız can. Robotlar geçse de 60 saniye boyunca yazmaya devam et.": "Unlimited lives. Keep typing for 60 seconds, even if robots get past you.",
  "SAVUNMAYI BAŞLAT": "START DEFENSE",
  "Kelimeyi yaz": "Type the word",
  "Otomatik ateş et": "Fire automatically",
  "Hattı koru": "Hold the line",
  "DOĞRU KELİME": "CORRECT WORDS",
  "KELİME / SANİYE": "WORDS / SECOND",
  "HATALI DENEME": "INCORRECT ATTEMPTS",
  "KAÇIRILAN KELİME": "MISSED WORDS",
  "Bir denemedeki yanlış harfler tek hata sayılır. Hız, yazılan kelime sayısının oynanan saniyeye bölünmesidir.": "Wrong letters within one attempt count as one error. Speed is completed words divided by active seconds played.",
  "MOD / ZORLUK DEĞİŞTİR": "CHANGE MODE / DIFFICULTY",
  "TEKRAR OYNA": "PLAY AGAIN",
  "HEDEF KELİMESİ": "TARGET WORD",
  "Başlamak için savunmayı etkinleştir": "Start the defense to begin",
  "Yaklaşan robotun kelimesini yaz…": "Type an approaching robot's word…",
  "Düşmanın üzerindeki kelimeyi yaz": "Type the word above an enemy",
  "OTOMATİK ATIŞ": "AUTO FIRE",
  "TÜRKÇE KELİMELER": "ENGLISH WORDS",
  "duraklat / devam et": "pause / resume",
  "SINIRSIZ CAN": "UNLIMITED LIVES",
  "3 CAN": "3 LIVES",
  "60 SANİYE": "60 SECONDS",
  "HIZINI DEĞİL, HAYATTA KALMANI TEST ET.": "TEST YOUR SURVIVAL, NOT JUST YOUR SPEED.",
  "PROTOTİP": "PROTOTYPE",
  "BİR SONRAKİ HAMLEYE HAZIRLAN": "GET READY FOR YOUR NEXT MOVE",
  "Kontrol": "Take",
  "sende.": "control.",
  "Elini ısıt. Hedefe git. Hareketini netleştir.": "Warm up. Find the target. Refine your movement.",
  "Önce isabet, sonra hız.": "Accuracy first, then speed.",
  "Rahat bir tutuşla başla.": "Start with a comfortable grip.",
  "Egzersiz seçimi": "Exercise selection",
  "Hedef avı": "Target hunt",
  "Akıcı takip": "Smooth tracking",
  "Beliren daireye tıkla. Hızlı geçiş ve isabet çalış.": "Click the circle. Practice quick transitions and accuracy.",
  "Tıklamadan hareketli dairenin üzerinde kal.": "Stay over the moving circle without clicking.",
  "TUR SÜRESİ": "ROUND DURATION",
  "ANTRENMANI BAŞLAT": "START TRAINING",
  "HEDEF AVI": "TARGET HUNT",
  "AKICI TAKİP": "SMOOTH TRACKING",
  "DURAKLAT": "PAUSE",
  "DEVAM ET": "RESUME",
  "Mouse antrenman alanı": "Mouse training area",
  "Küçük hareketler, daha iyi kontrol.": "Small movements, better control.",
  "Daireye sol tıkla. Her isabette yeni bir hedef belirir.": "Left-click the circle. Each hit reveals a new target.",
  "Mouse veya trackpad ile oyna · ESC ile duraklat": "Use a mouse or trackpad · ESC to pause",
  "Antrenman hedefi": "Training target",
  "Bir nefes molası.": "Take a breather.",
  "Süre durdu. Hazır olduğunda devam et.": "The timer is paused. Resume when you are ready.",
  "AYARLARA DÖN": "BACK TO SETTINGS",
  "Hedefler ekranın farklı noktalarında belirir.": "Targets appear at different positions.",
  "MEVCUT MOUSE HASSASİYETİNLE ÇALIŞIR": "USES YOUR CURRENT MOUSE SENSITIVITY",
  "ANTRENMAN TAMAMLANDI": "TRAINING COMPLETE",
  "Bir tur daha iyi.": "Better with every round.",
  "EGZERSİZ DEĞİŞTİR": "CHANGE EXERCISE",
  "Kısa turlarla başla. Bu bölüm sisteminin DPI veya hassasiyet ayarını değiştirmez; mevcut ayarına alışmanı sağlar.": "Start with short rounds. This exercise does not change your system DPI or sensitivity; it helps you get used to your current settings.",
  "Kelime tamamlanınca otomatik ateş edilir": "Complete a word to fire automatically",
  "GÖREV TAMAMLANDI": "MISSION COMPLETE",
  "SAVUNMA HATTI DÜŞTÜ": "DEFENSE LINE LOST",
  "Hattı korudun.": "You held the line.",
  "60 saniye boyunca direndin. Bir sonraki nöbete hazır mısın?": "You held out for 60 seconds. Ready for your next watch?",
  "Robotlar savunmayı aştı. Yeniden dene, kelimelere odaklan.": "The robots broke through. Try again and focus on the words.",
  "Yeni bir tur için tekrar oyna": "Play again to start a new round",
  "60 SANİYE TAMAMLANDI": "60 SECONDS COMPLETE",
  "Süre doldu.": "Time is up.",
  "Hız turu": "Speed round",
  " — yeni bir rekor için tekrar dene.": " — try again for a new record.",
  "Hedef yok edildi — sıradaki kelimeyi yaz": "Target destroyed — type the next word",
  "Eşleşme yok — Backspace ile düzelt": "No match — correct with Backspace",
  "DURAKLATILDI — ESC ile devam et": "PAUSED — press ESC to resume",
  "Hedef sana ulaştı — sıradaki kelimeyi yaz": "Target got past you — type the next word",
  "DURAKLATILDI": "PAUSED",
  "KESİNTİSİZ ATIŞ": "HIT STREAK",
  "Tıklamana gerek yok. İmleci hareketli dairenin içinde tut.": "No clicking needed. Keep your pointer inside the moving circle.",
  "Hedef kaybolmadan tıkla. Boşa tıklamalar isabet oranını düşürür.": "Click before the target disappears. Empty clicks lower your accuracy.",
  "Daire dolduğunda doğru yerdesin. Akıcı hareketlerle hedefi takip et.": "A filled circle means you are on target. Follow it with smooth movements.",
  "İSABET / SANİYE": "HITS / SECOND",
  "İSABET ORANI": "ACCURACY",
  "İSABET": "HITS",
  "TAKİP": "TRACKING",
  "BOŞA TIKLAMA": "EMPTY CLICKS",
  "KAÇAN HEDEF": "MISSED TARGETS",
  "ORT. TEPKİ SÜRESİ": "AVG. REACTION TIME",
  "HEDEFTE KALMA": "TIME ON TARGET",
  "HEDEF ÜZERİNDE": "ON TARGET",
  "İsabet oranı, tıkladığın hedeflerin tüm tıklamalarına oranıdır. Tepki süresi, vurduğun hedeflerin belirmesinden tıklamana kadar geçen süredir.": "Accuracy is successful hits divided by all clicks. Reaction time measures the delay between a hit target appearing and your click.",
  "Takip oranı, imlecin hedefin içinde kaldığı sürenin toplam tur süresine oranıdır.": "Tracking percentage is time spent inside the target divided by total round time.",
  "Sistemindeki azaltılmış hareket tercihi etkin.": "Your system's reduced motion preference is enabled.",
  "Menü ve düğme efektlerini aç / kapat": "Toggle menu and button effects",
  "ANİMASYON:": "ANIMATION:",
  "SES:": "SOUND:",
  "KAPALI": "OFF",
  "AÇIK": "ON",
  "saniye": "seconds",
  "sn": "s"
};
let language = 'tr';
try { language = localStorage.getItem('son-hat-language') === 'en' ? 'en' : 'tr'; } catch {}
const locale = language === 'en' ? 'en-US' : 'tr-TR';
const translationPattern = new RegExp("İsabet oranı, tıkladığın hedeflerin tüm tıklamalarına oranıdır\\. Tepki süresi, vurduğun hedeflerin belirmesinden tıklamana kadar geçen süredir\\.|Kısa turlarla başla\\. Bu bölüm sisteminin DPI veya hassasiyet ayarını değiştirmez; mevcut ayarına alışmanı sağlar\\.|Bir denemedeki yanlış harfler tek hata sayılır\\. Hız, yazılan kelime sayısının oynanan saniyeye bölünmesidir\\.|Takip oranı, imlecin hedefin içinde kaldığı sürenin toplam tur süresine oranıdır\\.|Daire dolduğunda doğru yerdesin\\. Akıcı hareketlerle hedefi takip et\\.|Sınırsız can\\. Robotlar geçse de 60 saniye boyunca yazmaya devam et\\.|Hedef kaybolmadan tıkla\\. Boşa tıklamalar isabet oranını düşürür\\.|60 saniye boyunca direndin\\. Bir sonraki nöbete hazır mısın\\?|Robotlar savunmayı aştı\\. Yeniden dene, kelimelere odaklan\\.|Tıklamana gerek yok\\. İmleci hareketli dairenin içinde tut\\.|3 can\\. Robotları durdur ve 60 saniye boyunca hayatta kal\\.|Daireye sol tıkla\\. Her isabette yeni bir hedef belirir\\.|hedefleri durdur ve son saniyeye kadar hayatta kal\\.|Beliren daireye tıkla\\. Hızlı geçiş ve isabet çalış\\.|Robotlar yaklaşıyor\\. Üzerlerindeki kelimeleri yaz,|Mouse veya trackpad ile oyna · ESC ile duraklat|Sistemindeki azaltılmış hareket tercihi etkin\\.|Elini ısıt\\. Hedefe git\\. Hareketini netleştir\\.|Hedefler ekranın farklı noktalarında belirir\\.|Tıklamadan hareketli dairenin üzerinde kal\\.|Üzerine doğru yürüyen üç boyutlu robotlar|Hedef sana ulaştı — sıradaki kelimeyi yaz|Kelime tamamlanınca otomatik ateş edilir|Hedef yok edildi — sıradaki kelimeyi yaz|HIZINI DEĞİL, HAYATTA KALMANI TEST ET\\.|Süre durdu\\. Hazır olduğunda devam et\\.|Menü ve düğme efektlerini aç / kapat|Başlamak için savunmayı etkinleştir|Küçük hareketler, daha iyi kontrol\\.|MEVCUT MOUSE HASSASİYETİNLE ÇALIŞIR| — yeni bir rekor için tekrar dene\\.|Eşleşme yok — Backspace ile düzelt|Yaklaşan robotun kelimesini yaz…|Düşmanın üzerindeki kelimeyi yaz|DURAKLATILDI — ESC ile devam et|Yeni bir tur için tekrar oyna|60 SANİYE BOYUNCA HATTI KORU|BİR SONRAKİ HAMLEYE HAZIRLAN|Rahat bir tutuşla başla\\.|Hız turu · sınırsız can|Önce isabet, sonra hız\\.|ETKİSİZ HALE GETİRİLEN|MOD / ZORLUK DEĞİŞTİR|Mouse antrenman alanı|ANTRENMAN TAMAMLANDI|60 SANİYE TAMAMLANDI|Hayatta kal · 3 can|duraklat / devam et|SAVUNMA HATTI DÜŞTÜ|En güçlü silahın,|ANTRENMANI BAŞLAT|Bir nefes molası\\.|Bir tur daha iyi\\.|EGZERSİZ DEĞİŞTİR|ORT\\. TEPKİ SÜRESİ|Kelime Savunması|Mouse Antrenmanı|KELİME SAVUNMASI|MOUSE ANTRENMANI|Antrenman bölümü|SAVUNMAYI BAŞLAT|Otomatik ateş et|KAÇIRILAN KELİME|TÜRKÇE KELİMELER|Antrenman hedefi|GÖREV TAMAMLANDI|KELİME / SANİYE|Egzersiz seçimi|KESİNTİSİZ ATIŞ|İSABET / SANİYE|SAVUNMA DURUMU|Bir şans daha\\.|HEDEF KELİMESİ|Hattı korudun\\.|HEDEF ÜZERİNDE|HATALI DENEME|OTOMATİK ATIŞ|HEDEFTE KALMA|kelimelerin\\.|Kelimeyi yaz|DOĞRU KELİME|SINIRSIZ CAN|AYARLARA DÖN|DURAKLATILDI|İSABET ORANI|BOŞA TIKLAMA|Gece nöbeti|Bir kelime\\.|TEKRAR OYNA|Akıcı takip|AKICI TAKİP|Süre doldu\\.|KAÇAN HEDEF|KALAN SÜRE|Hattı koru|TUR SÜRESİ|ANİMASYON:|Bir atış\\.|OYUN MODU|60 SANİYE|Hedef avı|HEDEF AVI|PROTOTİP|DURAKLAT|DEVAM ET|Hız turu|SON HAT|Kontrol|KLAVYE|SEKTÖR|ZORLUK|sende\\.|İSABET|KAPALI|saniye|Kolay|3 CAN|TAKİP|Orta|SES:|AÇIK|Zor|sn", 'g');
function translate(text) {
 if (language !== 'en') return text;
 return text.replace(translationPattern, match => translations[match]);
}
function lockLanguage(locked) { const select=document.getElementById('language'); if(select) select.disabled=locked; }
document.documentElement.lang=language;
document.addEventListener('DOMContentLoaded',()=>{
 const walker=document.createTreeWalker(document.documentElement,NodeFilter.SHOW_TEXT);
 const nodes=[]; while(walker.nextNode()) if(!['SCRIPT','STYLE'].includes(walker.currentNode.parentElement?.tagName)) nodes.push(walker.currentNode);
 for(const node of nodes) node.nodeValue=translate(node.nodeValue);
 for(const el of document.querySelectorAll('[aria-label],[placeholder],[title]')) for(const attr of ['aria-label','placeholder','title']) if(el.hasAttribute(attr)) el.setAttribute(attr,translate(el.getAttribute(attr)));
 const select=document.getElementById('language'); select.value=language;
 select.addEventListener('change',()=>{try {localStorage.setItem('son-hat-language',select.value);} catch {select.value=language;return;} location.reload();});
});
