(() => {
 const en=typeof language!=='undefined'&&language==='en';
 const t=(tr,english)=>en?english:tr;
 const make=(tag,text)=>{const el=document.createElement(tag);el.textContent=text;return el;};
 const button=make('button',t('Gizlilik ve kullanım','Privacy & terms'));button.className='privacyOpen';button.type='button';
 const dialog=document.createElement('dialog');dialog.className='scoresDialog privacyDialog';dialog.setAttribute('aria-labelledby','privacyTitle');
 const title=make('h2',t('Gizlilik ve kullanım','Privacy & terms'));title.id='privacyTitle';
 const close=make('button',t('Kapat ×','Close ×'));close.type='button';close.onclick=()=>dialog.close();
 dialog.append(title,close,make('p',t('Son güncelleme: 1 Ekim 2026','Last updated: October 1, 2026')));
 const sections=[
 ['Proje ve iletişim','Project & contact','Son Hat, ücretsiz bir klavye ve mouse antrenmanı projesidir. Proje hesabı: ahmetsen532. Soru ve geri bildirim için aşağıdaki GitHub bağlantısını kullanabilirsin. Herkese açık bildirimlere kişisel veya hassas bilgi ekleme.','Son Hat is a free keyboard and mouse training project. Project account: ahmetsen532. Use the GitHub link below for questions and feedback. Do not include personal or sensitive information in public reports.'],
 ['Tarayıcıda neler saklanır?','What is stored in your browser?','Dil ve animasyon tercihin, seçim yaptığında bu cihazda hatırlanır. Skor kaydı başlangıçta kapalıdır. Skorlarım bölümünden açarsan son 5 turun tarihi, modu, zorluğu, dili, süresi ve oyun istatistikleri ile kişisel rekorların localStorage alanında saklanır. Kayıt tercihin de aynı yerde tutulur. Geçiş animasyonu kodu, varsa geçici bir sessionStorage kaydını okur ve siler.','Language and animation preferences are remembered on this device when you choose them. Score saving is off by default. If you enable it in My scores, localStorage stores the dates, modes, difficulty, language, duration and statistics of your last five rounds, plus personal bests. Your storage preference is also saved there. Transition code reads and removes a temporary sessionStorage record if present.'],
 ['Amaç, süre ve kontrol','Purpose, retention & control','Bu kayıtlar tercihlerini hatırlamak ve kişisel sonuçlarını göstermek içindir; uygulama kodu bunları sunucuya göndermez. Üyelik, reklam veya ziyaretçi analiz aracı bulunmaz. Son 5 tur döngüsel yenilenir; rekorlar ve tercihler sen silene veya tarayıcı site verilerini temizleyene kadar kalır. Skorlarım bölümünden yeni skor kaydını kapatabilir, mevcut skorları silebilirsin. Diğer tercihleri silmek için tarayıcının site verilerini temizle. Farklı cihaz, tarayıcı veya site adresleri arasında eşitleme yapılmaz.','These records remember your choices and display personal results; application code does not send them to a server. There are no accounts, advertising or visitor analytics tools. Only the latest five rounds are retained; records and preferences remain until you or your browser clear them. My scores lets you disable new score saving or delete existing scores. Clear site data in your browser to remove other preferences. Data is not synced between devices, browsers or site addresses.'],
 ['Barındırma hizmeti','Hosting service','GitHub Pages üzerinde yayınlanan sürümde GitHub, güvenlik amacıyla ziyaretçilerin IP adreslerini kaydeder. Bu işlem tarayıcıdaki skor kaydından ayrıdır. Yerel Node.js sürümümüz ayrıca erişim günlüğü yazmaz; farklı bir barındırma hizmeti kullanılırsa o hizmetin uygulamaları da geçerli olabilir.','For the version hosted on GitHub Pages, GitHub logs visitor IP addresses for security. This is separate from local score storage. Our local Node.js server does not write access logs; another hosting provider may apply its own practices.'],
 ['Kullanım koşulları','Terms of use','Oyun, eğlence ve pratik amacıyla sunulur; sonuçlar profesyonel bir beceri ölçümü veya gelişim garantisi değildir. Hizmetin kesintisiz çalışması veya yerel kayıtların her koşulda korunması garanti edilmez. Yerel skorlar resmi bir rekabet sıralaması değildir. Bu açıklama kanundan doğan haklarını sınırlamaz.','The game is provided for entertainment and practice. Results are not professional skill assessments or a guarantee of improvement. Uninterrupted availability and preservation of local data cannot be guaranteed. Local scores are not an official competitive ranking. These terms do not limit your statutory rights.']
 ];
 for(const [trHead,enHead,trBody,enBody] of sections)dialog.append(make('h3',t(trHead,enHead)),make('p',t(trBody,enBody)));
 for(const [text,url] of [[t('Proje ve geri bildirim','Project & feedback'),'https://github.com/ahmetsen532/Klavye-Mouse-Oyunu'],[t('GitHub Pages veri toplama açıklaması','GitHub Pages data collection'),'https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages'],[t('GitHub gizlilik bildirimi','GitHub privacy statement'),'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement']]){const p=make('p',''),a=make('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);dialog.append(p);}
 dialog.addEventListener('keydown',event=>{if(event.key==='Escape')event.stopPropagation();});
 button.onclick=()=>{if(typeof running!=='undefined'&&running&&!paused)pause();else if(typeof round!=='undefined'&&round&&!round.done&&!paused)pause();dialog.showModal();};
 document.body.append(button,dialog);
})();
